main: me.SuperRonanCraft.BetterRTP.BetterRTP
version: ${project.version}
name: SimpRTP
author: SuperRonanCraft
folia-supported: true #As of 3.6.8 thanks to LOOHP#6007, TechnicallyCoded#9095 and loving11ish#2066
softdepend:
    - Vault
    - Multiverse-Core #Forcing Multiverse to load BEFORE SimpRTP
    - Essentials #adds `/back` support
    - PlaceholderAPI
api-version: '26.1'

commands:
    srtp:
        aliases: [simprtp, rtp, randomtp, wild, wildtp]
        description: 随机传送到安全位置

permissions:
    simprtp.*:
        children:
            simprtp.use: true
            simprtp.world.*: true
            simprtp.bypass.*: true
            simprtp.player: true
            simprtp.reload: true
            simprtp.biome: true
            simprtp.language: true
            simprtp.version: true
    simprtp.world.*:
        description: 可在所有已启用的世界中随机传送
    simprtp.bypass.*:
            children:
                simprtp.bypass.cooldown: true
                simprtp.bypass.delay: true
                simprtp.bypass.economy: true
    simprtp.use:
        description: 使用随机传送指令
        default: true
    simprtp.language:
        description: 选择个人 SimpRTP 消息语言
        default: true
    simprtp.version:
        description: 查看当前插件版本
    simprtp.world:
        description: 使用世界随机传送指令
    simprtp.player:
        description: 随机传送其他玩家
    simprtp.biome:
        description: 随机传送到指定生物群系
    simprtp.location:
        description: 使用指定位置随机传送
    simprtp.group.*:
        description: 使用权限组专用的随机传送参数
    simprtp.sign:
        description: 创建随机传送指令牌
    simprtp.bypass.cooldown:
        description: 绕过冷却时间
    simprtp.bypass.delay:
        description: 绕过传送等待
    simprtp.bypass.economy:
        description: 绕过经济收费
    simprtp.bypass.hunger:
        description: 绕过饥饿值检查
    simprtp.reload:
        description: 重载插件配置
        default: op
    simprtp.info:
        description: 查看可使用随机传送的世界信息
        default: op
    simprtp.test:
        description: 在调试模式下测试粒子、药水和声音效果
        default: op
    simprtp.edit:
        description: 编辑默认或自定义世界的传送中心和半径
        default: op
